services:
  simple-apps:
    container_name: ct-simpleapps-prod-pipeline3
    build: ./app
    image: stieady07/img-simpleapps:v1-stable
    ports:
    - "10003:3000"
    restart: always
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 128M
