services:
  simple-apps:
    container_name: ct-simpleapps
    build: ./app
    ports:
    - "11000:3000"
    restart: always
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 128M
